### ISSUE TITLE
TrueView Compatibility: Block and Insert

### ISSUE THREAD

**Issue by nzain** [ixmilia/dxf#100]
While implementing a rather complex 3D DXF export, I test with various applications to validate my experiments:

- ODA Drawings Explorer (free tool you suggested)
- DWG TrueView (free tool from Autodesk)
- ProgeCad (my company has a license)

While the ODA explorer and ProgeCad show expected results, TrueView keeps freezing as soon as I add a `DxfBlock`. I don't get an error message and I couldn't find logs to identify possible problems... In your readme.md you mention that AutoCad doesn't always like this library's output:

> And the following entities might not open in AutoCAD if written with missing information. [...] `DxfInsert`

Did you ever succeed in creating a block+insert? What is the correct way to add block+insert? I couldn't find any clues in the spec.

**To Reproduce**
Shortened source code to produce a freezer-dxf file for TrueView looks like this:

```csharp
    DxfFile dxf = new DxfFile();
    dxf.Header.SetDefaults();
    dxf.Header.Version = DxfAcadVersion.R2013;
    dxf.Header.DrawingUnits = DxfDrawingUnits.Metric;
    dxf.Header.UnitFormat = DxfUnitFormat.Decimal;
    dxf.Header.DimensionUnitFormat = DxfUnitFormat.Decimal;
    dxf.Header.DefaultDrawingUnits = DxfUnits.Meters;
    dxf.Header.UnitPrecision = 3;
    dxf.Header.DimensionUnitToleranceDecimalPlaces = 3;

    // adding simple entities (works fine)
    dxf.Entities.Add(new DxfLine(new DxfPoint(0, 0, 0), new DxfPoint(1, 1, 0)));

    // add a block (TrueView freezes)
    DxfBlock block = new DxfBlock
    {
        Name = "foo",
        IsAnonymous = true, // dxf spec: "generated by an application"
        BasePoint = new DxfPoint(0, 0, 0),
        Entities = { new DxfLine(new DxfPoint(0, 0, 0), new DxfPoint(2, 0, 0)) }
    };
    dxf.Blocks.Add(block);
    dxf.BlockRecords.Add(new DxfBlockRecord{Name = block.Name}); // ProgeCad shows warning, if blockrecord is missing
    dxf.Entities.Add(new DxfInsert
    {
        Name = block.Name,
        Location = new DxfPoint(2,2,0)
    });

    // save
    dxf.Normalize();
    using (FileStream fs = File.Create(filename))
    {
        dxf.Save(fs);
    }
```

I have tested with TrueView 2019 and 2017, same problem - it freezes completely when opening that file. Any ideas what could be missing?

The more I use this library (and read DXF spec if something doesn't work), the more I like this project. The sheer mass of DXF properties, sometimes optional, often context-dependent makes it almost impossible to create spec-conform output. Its good to have a library handling a large part of that hassle! 👍

**Comment by nzain** [comment]
Okay.. setting `blockRecord.LayoutHandle` (your guess) did not work, same result (TrueView crashes).

To get more insights, I opened the [ixmilia.dxf.txt](https://github.com/IxMilia/Dxf/files/2787254/ixmilia.dxf.txt) file created from my code with ProgeCad and saved it without further changes. File size jumps from 14KB to 166KB... and TrueView does not crash when opening this [ixmilia saved by progecad.dxf.txt](https://github.com/IxMilia/Dxf/files/2787255/ixmilia.saved.by.progecad.dxf.txt) file - however, the block/insert is not visible. Next, I've created the same drawing (single line and one block with another line) in ProgeCad from scratch and saved it as [progecad.dxf.txt](https://github.com/IxMilia/Dxf/files/2787256/progecad.dxf.txt). This one opens fine in TrueView.

Opening the library-generated file in the online-viewer https://viewer.autodesk.com crashes as well
> TranslationWorker-InternalFailure Unrecoverable exit code from extractor: -1073741831

and seven (!) e-mails tell me:

> There was an error processing your file.
> 
> Possible issues could be:
> - Your file may have external references which are not currently supported.
> - You may have used an older file version, which may not work.
> - Your file may be corrupted or encrypted.

Comparing DXF files is quite complicated... my findings so far:

- your library does not set a default layer ("0") for a block, ProgeCad does. However, setting the `DxfBlock.Layer` manually to "0" didn't change anything.
- your library creates a `DxfSequend` entity (in ENTITIES, after `DxfInsert`) that is deleted by ProgeCad on save and ProgeCad would not create it either, when drawing from scratch. Maybe this is related? I did not yet understand what this Sequend is.
- The block-type flags (code 70) are all unset in all files (at least your library says that), I guess these are not the problem (Note: I removed the `block.IsAnonymous = true` call, had no effect.)
- In addition to the two default blocks "*MODEL_SPACE" and "*PAPER_SPACE", ProgeCad create a block named "_dot" with a line and an lw-polyline to confuse me even more.

Right now I'm downloading AutoCad LT trial. I'll create the same drawing in AutoCad LT and upload it here, maybe we can diagnose the problem by comparing the files. Installer forces me to close browser now...

**Comment by nzain** [comment]
I've confirmed AutoCad LT 2019 crashes (freezes) in the exact same way as TrueView. No error message, unfortunately. Amazing software! Finally I created the same drawing from AutoCad LT 2019: [autocad.dxf.txt](https://github.com/IxMilia/Dxf/files/2787556/autocad.dxf.txt)

Comparing `ixmilia.dxf` with `autocad.dxf` shows a ton of differences and I find it extreemly difficult to interpret. I extracted the relevant parts (guessing here: BLOCK_RECORD, BLOCK, INSERT) and eventually you see something odd. Green parts are written by AutoCad, not by IxMilia.Dxf.

```diff
BLOCK_RECORD
   5
-19
+288
+102
+{ACAD_XDICTIONARY
+360
+29C
+102
+}
 330
-16
+1
 100
 AcDbSymbolTableRecord
 100
 AcDbBlockTableRecord
   2
 foo
 340
-1E
+0
+310
+2800000020000000200000000100200000000000001000000100000001000000000000000000000003000000302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821
+310
+FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF3028
+ [...] LOTS of 310 groups removed for readability
+310
+302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF302821FF
+102
+{BLKREFS
+331
+28C
+102
+}
  70
-     0
+     6
 280
      1
 281
-     1
+     0
+1001
+AcDbDynamicBlockGUID
+1000
+{050DC8DC-71DE-9C4F-B9BA-2786CA056BF3}
```

```diff
 BLOCK
   5
-1E
+289
+330
+288
 100
 AcDbEntity
   8
 foo
 
   0
 LINE
+  5
+29B
+330
+288
 100
 AcDbEntity
   8
 0
-370
-     0
-430
-
-440
-        0
-284
-     0
 100
 AcDbLine
  10
 ENDBLK
```

```diff 
 INSERT
   5
-21
+28C
+330
+1F
 100
 AcDbEntity
   8
 0
-370
-     0
-430
-
-440
-        0
-284
-     0
 100
 AcDbBlockReference
   2
 foo
  20
 2.0
  30
 0.0
-210
-0.0
-220
-0.0
-230
-1.0
-  0
-SEQEND
-  5
-22
-100
-AcDbEntity
-  8
-0
-370
-     0
-430
-
-440
-        0
-284
-     0
```

**Comment by brettfo** [comment]
Thank you for this investigation.  I'm still slowly going through it on my end when I have the time.

**Comment by nzain** [comment]
Just for your interest: we tested the commercial package from open design alliance (core part has 60MB). It took us 3 days and several support e-mails until we managed to write a dxf file with a single line. Funny enough.. and DWG TrueView hangs when opening this file. I hope, we can convince the management to keep IxMilia.Dxf for its great API and simplicity.

**Comment by nzain** [comment]
I found out how to get some insight _why_ AutoCAD and/or TrueView crash. When the app crashes, you can expand the _command history_ like this:
![image](https://user-images.githubusercontent.com/13961979/72890981-78e26f80-3d13-11ea-89b6-f4389cb946f5.png)

and it will reveal why it crashed. For my sample file above this is:
> The following error was encountered while reading
> in LINE starting at line 1972:
> Handle missing
> Invalid or incomplete DXF input -- drawing discarded.

Thats probably the second `DxfLine` _inside_ the `DxfBlock`. This confirms your guess about missing handles. Eventually we can narrow this down. I'll spend the next days learning & experimenting with handles.

**Comment by nzain** [comment]
Guess I found the crucial problem: Entities inside `DxfBlock.Entities` will not receive handles. Thus, the code 5 pair is missing and Autodesk complains. Adding some random large number (not already in use) manually in the text file, like so:

```
  0
LINE
  5
9999
```

will prevent the crash. True View will not display this line; it complains: `DXF file's HANDSEED '26' is too low.`

Now the mission is clear. I realized that `DxfBlock.GetChildItems()` does not return its own entities. Returning them here still does not assign a handle to them. I'm trying to find the right spot so that a handle is assigned.

**Comment by nzain** [comment]
Even if a handle is set, your code says `entities in blocks never have handles`:
https://github.com/ixmilia/dxf/blob/3f9542ecbdfde6de94ff044566aa6dbd24886dc1/src/IxMilia.Dxf/Blocks/DxfBlock.cs#L160-L161

Looking at the autocad.dxf file, both lines (independent and within block) have their code 5 pair written (their values are 286 and 29B respectively).

When I do explicitly output the handles inside a block, the code 5 pair is written, True View does neither crash, nor complain... nor does it display the line inside my block. Maybe my mission is not so clear :-(

**Comment by nzain** [comment]
@brettfo what makes you think 

> entities in blocks never have handles

I would make a PR for this to further improve Autodesk compatibility (AutoCAD & co). However, your comment suggests this might be a bad idea.

**Comment by brettfo** [comment]
Reading through your previous comments your 3 points in `Summary of required changes` looks to be correct.  As for the block/entity owner handle I'm not sure yet.

If you want to work on a PR for the 3 points, I'd be happy to take it, especially if you have a copy of AutoCAD on your end to test with.
