### ISSUE TITLE
XML documentation file is missing in the NuGet package

### ISSUE THREAD

**Issue by stijnherreman** [ixmilia/dxf#114]
Some of the public API has XML documentation comments, but the NuGet package doesn't come with an XML documentation file.

Can you add the file to the NuGet package?

**Comment by brettfo** [comment]
Just added commit 25c88251b756afcb0df40a30976ffe49251a3cc0 to ensure the doc comments are built and included in the package.

I'm not yet at a point where I'm ready to release another version to NuGet, though, but if you clone/build locally you'll now get `IxMilia.Dxf.xml` placed in the appropriate output directory.
