### ISSUE TITLE
Consider adding license information to the nuget (visible on nuget.org)

### ISSUE THREAD

**Issue by nzain** [ixmilia/dxf#120]
Package consumers often care about the license (can I use the package? updating EULA on nuget upgrades, etc). It would be nice to see the projects license information

https://github.com/ixmilia/dxf/blob/master/License.txt

directly on https://www.nuget.org/packages/IxMilia.Dxf/

The new `csproj` format defines several properties related to licenses: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties
Interestingly, an URL is deprecated, and [SPDX identifiers](https://spdx.org/licenses/) are preferred. That would be `Apache-2.0` in this case.

**Comment by brettfo** [comment]
Good call!  Updated `.csproj` in d308feb5233a42746f8aa0ff3a7d21c5b89c7d7f.  Next NuGet release should have it.
