### ISSUE TITLE
Drawing order

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [ixmilia/dxf#137]
When I load a dxf file, I get a list of entities. Is this also the drawing order of the elements? When I draw that entity list, I get not the same result, when I open it with Autocad. Any ideas?
Thanks.
Andreas

**Comment by brettfo** [comment]
AutoCAD uses the `SORTENTSTABLE` object to specify the drawing order.  Support for that is experimental at best in this project, but you could likely do something like this:

``` csharp
IEnumerable<DxfEntity> GetEntitiesInDrawOrder(DxfFile drawing)
{
    var sortEnts = drawing.Objects.OfType<DxfSortentsTable>().FirstOrDefault();
    if (sortEnts != null)
    {
        // found entities in drawing order
        return sortEnts.Entities;
    }

    // no drawing order specified, use declaration order
    return drawing.Entities;
}
```
