### ISSUE TITLE
[convenience utils] [feature request] Please add method or class to convert lwPolyline to set of lines and arcs

### ISSUE THREAD

**Issue by uzername** [ixmilia/dxf#161]
lwPolyline is defined as set of points and associated "bulge" value for each of them. 
Suggestion : please, add a convenience method which takes lwPolyline (or just Polyline) instance and returns array of DxfEntities : arcs and lines. 
While reading DXF geometry and processing it I operate in terms of arcs and lines. Please, add such utility method, I struggle parsing Polyline geometry to arcs and lines.

**Comment by sampletext32** [comment]
@uzername, PR was just merged. Would you kindly test the feature and respond with some feedback?
