### ISSUE TITLE
IEnumerable<DxfEntity> AsSimpleEntities() doesn't take care of the Layer's name of resulting entities.

### ISSUE THREAD

**Issue by SerjDrob** [ixmilia/dxf#175]
For example after following statement:

var temp = Document.Entities.OfType<DxfLwPolyline>().First().AsSimpleEntities();

All resulting entities of the temp will have property "Layer" which value is always "0" despite on Layer's value of the initial DxfLwPolyline object.

**Comment by brettfo** [comment]
Thank you for finding and filing the issue.  I've fixed the bug in commit 1e2f82e50d08eccf46b1fed2da545eb27fb4f2da which I just pushed to `main`.
