### ISSUE TITLE
Unable to associate entity to Dimension, eg. DxfDiameterDimension

### ISSUE THREAD

**Issue by ChrisSmales** [ixmilia/dxf#177]
I am struggling to work out how to use the various Dimension entities such as DxfDiameterDimension. I was assuming for such a dimension a Circle entity would be associated with it in some way and from that the dimension entity would determine the diameter. Would if be possible to provide an example of the use of these objects ?

**Comment by brettfo** [comment]
I just pushed a commit to main that contains an example of adding a dimension, but the short answer is that there is no association in the DXF file between the dimension entity and the value being measured; it's entirely up to you to do this.

This is what the new example looks like in LibreCAD 2.1.3:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/926281/164295373-fefa48ff-d34f-4f54-9592-c3807d08ac09.png">

But note, however, that `DefinitionPoint1` and `DefinitionPoint2` can be set to anything resulting in the non-sensical:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/926281/164295538-e2eb10da-df4c-4832-8454-32c10571b62d.png">
