### ISSUE TITLE
Offset of a polyline.

### ISSUE THREAD

**Issue by VinayFdes** [ixmilia/dxf#178]
How to create a polyline offset to an already existing polyline?
Please refer to the image. I want to create a line(the red one ) at an offset of say 5mm. How to maintain the 'curve' just like existing line ?
![image](https://user-images.githubusercontent.com/98016592/164238471-82ebd61f-aa73-4334-954f-759d576a8380.png)

**Comment by nzain** [comment]
You cannot offset _any_ polyline. You can, of course, offset line segments
and you can offset arc segments (need to understand bulge first).

However, some weird cases are degenerate:
- consider a line from A to B and the subsequent segment going back to A
- consider an arc segment with radius R: you cannot offset into the arc
interior farther than R

And whenever the polyline segments change direction (discontinuous 1st
derivative), such an algorithm would need to calculate intersection points
for each offset segment. Not impossible, but not trivial either. Your
sample looks smooth and an offset polyline would be reasonable. However, I
think such logic is too specialized to be implemented in this library. This
is not about DXF functionality, but goes a lot deeper into general geometry.

If you want to solve this on your own, try to construct arc segments from
(point,point,bulge) first. When you have the center, it is easy to
calculate a simple offset. Eventually you can skip the segment-segment
intersection, if your polyline is smooth.

Best,
  Patrick

VinayFdes ***@***.***> schrieb am Mi., 20. Apr. 2022, 15:16:
