### ISSUE TITLE
SPATIAL_FILTER code 40 issue

### ISSUE THREAD

**Issue by rocchellid** [ixmilia/dxf#192]
I have DXF (AutoCAD 2018) that crashed while loading. Analyzing the problem I saw that every 12 elements of code 40 you group them. In the DXF there are 24, but you don't add the first one to the list so in the end the second list has 11 and the assert intervenes.
The 40 data starts at line 3047813 of the DXF file.
If I also add the first element, as you can see, the DXF is loaded correctly (3.png on the right; AutoCAD on the left).
I'll send you the DXF privately.
Regards
Davide

![1](https://user-images.githubusercontent.com/80352691/215191523-0ff4729a-0f31-4106-a150-2fba2bd3f3d4.png)

![2](https://user-images.githubusercontent.com/80352691/215191545-119a593e-35e7-4b35-8865-8af6cbb6f84a.PNG)

![3](https://user-images.githubusercontent.com/80352691/215192977-7f010a9d-6742-4a75-8eac-4ef237d60253.png)

**Comment by brettfo** [comment]
Thank you for filing the issue and sending me the drawing.  I wasn't properly accounting for the `IsFrontClippingPlane` flag.  Fix has been pushed to `main`.
