### ISSUE TITLE
Mirrored coordinates of some entries.

### ISSUE THREAD

**Issue by vnazar1985** [ixmilia/dxf#203]
Hello.
I have some files that are incorrectly processed by the library, but open correctly in ordinary viewers and graphic editors.
I looked at the file and I see there the coordinates of the object that correspond to the coordinates read by the library, but somehow these coordinates should have turned into correct ones. So probably some kou reaction is missed.
[Part - 1.dxf.txt](https://github.com/ixmilia/dxf/files/14345345/Part.-.1.dxf.txt)

I provide an example of one such file.

![image](https://github.com/ixmilia/dxf/assets/64702234/e7b70fac-e099-4382-aaa1-926cf3984109)
This applies to the circle. its coordinates seem to be correct, but in fact they are not.

This is how the library handles it:
![image](https://github.com/ixmilia/dxf/assets/64702234/1a19a6e2-f6c5-4523-8196-3a9cbe53be48)
p.s. Do not pay attention to the coordinates in the example image, there the figure is turned around, but it does not change the essence of the problem, just the circle is not in the middle.
![image](https://github.com/ixmilia/dxf/assets/64702234/353c614f-530b-431c-a7c0-df39300ffeb2)
![image](https://github.com/ixmilia/dxf/assets/64702234/9314c221-3e8d-4a34-9641-fd03a5ac0fdc)

As you can see, the X coordinate is negative in circles and positive in lines.
The same applies to other elements, they are all positive, except for the circle.

This is how it should look.
![image](https://github.com/ixmilia/dxf/assets/64702234/fa26ac6b-d2db-4918-b5de-d317a8715cf9)

That is, the library reads the coordinates correctly, but some transformation must still take place with them so that the circle is inside the figure.

Thank you.

**Comment by brettfo** [comment]
What viewers are you using and how was the DXF file created?  The DXF snippet you posted appears correct, but with one caveat; look down to lines 155-160:

```
210
0.0
220
0.0
230
-1.0
```

Those codes represent the circle's normal vector which means the circle isn't "facing" the screen, it's "facing" away.  The normal vector (called "extrusion" by the DXF spec) is usually `(0,0,1)`, but here it's `(0,0,-1)`.

**Comment by vnazar1985** [comment]
Thank you for your reply. How this file was generated I do not know, it is a custom file, researching its origin is difficult.
But yes, I understood your answer, and came to the same conclusion when I was trying to solve this yesterday.
So this vector really tells about the inversion of the plane. But this does not indicate the direction of reversal. It can be due to X, due to Y or other conditions. I solved it for myself by Mirroring the X coordinate, but this is not a valid solution, it just seemed better to me.
So I agree that the library reads this data correctly, and it even reads that vector.
But how to correctly process it remains to be discovered, although it is possible outside the library.
In any case, such a vector is not unambiguous, which creates problems due to the absence of rules.
Perhaps you have information on the sequence of use of this vector?
Thank you.

**Comment by brettfo** [comment]
Your behavior of mirroring the X coordinate is correct.  DXF files use [Autodesks's Arbitrary Axis Algorithm](https://help.autodesk.com/view/OARX/2020/ENU/?guid=GUID-E19E5B42-0CC7-4EBA-B29F-5E1D595149EE) which states how to compute the axes, and in this instance, the first clause is relevant (written differently for clarity:

```
if (abs(normal.X) < 1/64 && abs(normal.Y) < 1/64))
{
    xAxis = (0, 1, 0) X normal; // the result of this is that the object's x axis is now (-1, 0, 0), which is the mirroring you did
}
```
