### ISSUE TITLE
Is there any way to fill color in more than four vertexes or less than four vertexes polyline area?

### ISSUE THREAD

**Issue by idazhenhan** [IxMilia/Dxf#63]
I am using DxfSolid to fill color for a polyline entity, I saw it supports just four vertexes.
If a polyline entity has three or five(or much more) vertexes, the DxfSolid  setting will be invalid.
Can you show me some examples of how to fill a  polyline with custom color in right way?

Thank you!

**Comment by brettfo** [comment]
Admittedly I'm not very familiar with the `SOLID` entity type (represented by `DxfSolid` in this code base) but according to the official AutoCAD spec [here (page 152)](http://images.autodesk.com/adsk/files/autocad_2014_pdf_dxf_reference_enu.pdf) (PDF warning), `SOLID` entities have exactly 4 vertices and you'd have to use a polyline for less/more.

**Comment by idazhenhan** [comment]
Thank you for your response.. It seems I have to find another way to fullfill my needs, the spec may be helpful :]

**Comment by idazhenhan** [comment]
Sorry for the reopen operate.

Is there have a plan to support for [Dxf HATCH(page 98)](http://101.96.10.70/images.autodesk.com/adsk/files/autocad_2014_pdf_dxf_reference_enu.pdf) and [Dxf Boundary Path Data(page 101)
](http://101.96.10.70/images.autodesk.com/adsk/files/autocad_2014_pdf_dxf_reference_enu.pdf)?, I found these two parts are very useful to resolve problems like my needs.

**Comment by brettfo** [comment]
I do eventually want to support `HATCH` entity types as part of #24 (and the corresponding boundary path and pattern data), but it's a complex enough entity that I don't see myself getting around to it any time soon.

**Comment by idazhenhan** [comment]
Get it. Thanks!
