### ISSUE TITLE
Polylines in blocks are not parsed correctly

### ISSUE THREAD

**Issue by arendvw** [IxMilia/Dxf#65]
The polylines in the block in the attached file are not parsed correctly. The block "Block02" contains 1 polyline, with 4 vertices. See test-case: [test4.zip](https://github.com/IxMilia/Dxf/files/697652/test4.zip)

The file was generated with Rhinoceros 3d in an Autocad 2004 format. Similar effects were to be seen with different export versions, and files generated with Adobe Illustrator.

Reproducing can be done using the following code:

            using (var fs = new FileStream("data/test4.dxf", FileMode.Open))
            {
                var dxfFile = DxfFile.Load(fs);
                var blocks = dxfFile.Blocks;
                var exampleBlock = blocks.Where(blk => blk.Name == "Block02").First();
                foreach (var item in exampleBlock.Entities)
                {
                    Console.WriteLine(item.EntityType);
                }
                var polyline = (DxfPolyline)exampleBlock.Entities.First();

                Console.WriteLine("Polyline has {0} vertices", polyline.Vertices.Count);
            }
            Console.ReadLine();

Will give the following output:

	Polyline
	Vertex
	Vertex
	Vertex
	Vertex
	Seqend
	Polyline has 0 vertices

Where of course 1 Polyline with 4 vertices is expected (without vertices as seperate entities, or seperate Seqend entities)

**Comment by brettfo** [comment]
Good find!  I've fixed the issue in `master`, the change is here: cb2e0bf6d7630cbdda168250190b6fd01624e70f.
