### ISSUE TITLE
charset "gb2312" is not supported by this libaray 

### ISSUE THREAD

**Issue by whuaegeanse** [IxMilia/Dxf#67]
When reading a dxf file which contains simplified Chinese, the library can not read it correctly.

**Comment by whuaegeanse** [comment]
Does the class DxfAsciiReader  not support other charset except Ascii? The function of the DxfAsciiReader use default charset encoding. I changed the code into var streamReader = new StreamReader(stream, system.text.encoding.default); Then the dxf file is readed correctly.

**Comment by brettfo** [comment]
> Does the class DxfAsciiReader not support other charset except Ascii?

Correct.  According to the official spec (See the README for links) only ASCII encoding is supported.  I've updated the reader/writer to enforce this.
