### ISSUE TITLE
Can´t open files from server with readonly permission

### ISSUE THREAD

**Issue by Idaps** [IxMilia/Dxf#76]
As the title says, I encountered the problem that I can´t open DXF-Files from a server where I only have permission to read.

I open it as its said in the description
`using (FileStream fs = new FileStream(path, FileMode.Open))
                {
                    dxf = DxfFile.Load(fs);
                }`

The Exception that I get from it says that the access got denied.
Is it possible to do something against it without changing permission, or does the library need to be able to do writing?

**Comment by nzain** [comment]
This is not a problem with the library. Open the file with read-only permission:
```
File.Open(filePath, FileMode.Open, FileAccess.Read)
```
or using the `FileStream` constructor:
```
new FileStream(filePath, FileMode.Open, FileAccess.Read)
```
