### ISSUE TITLE
Is Polyline containing Arcs supported? 

### ISSUE THREAD

**Issue by kub1x** [IxMilia/Dxf#90]
I have a DXF file with Polyline containing Line and Arc segments. When I parse Polyline, all I see is Vertices. How can I reconstruct the original polyline? In other words, how do I get properties of such an Arc, like center, radius, from/to angle, when all I have is a Vertex? 

Looking for `Arc`, I have found this TODO comment in the source. Does it mean Polyline with Arcs is not supported yet?
https://github.com/IxMilia/Dxf/blob/821416ea712a8acad118ac01a9a3440bba94eb12/src/IxMilia.Dxf/Entities/DxfPolyline.cs#L165

**Comment by brettfo** [comment]
Yes, arc-containing polylines are supported, but the DXF spec doesn't make it easy.

The arcs have to be manually reconstructed by iterating through each vertex which will give you a start and end point for each segment and arc. If a given segment's `Bulge` property is nonzero then an arc can be created. See [this](http://help.autodesk.com/view/OARX/2019/ENU/?guid=GUID-0741E831-599E-4CBF-91E1-8ADBCFD6556D) for details on how to compute this.
