### ISSUE TITLE
about Table

### ISSUE THREAD

**Issue by 748448660** [IxMilia/Dxf#91]
Hi,
   which DXFVersion support to write the table ? 
thank you.

**Comment by brettfo** [comment]
All versions of DXF files support tables, but the `AppId` and `DimStyle` tables are only supported on R12 or newer and `BlockRecord` tables are R13 or newer.  You can set the file version before writing like this:

``` C#
DxfFile file = new DxfFile();
// ...
file.Header.Version = DxfAcadVersion.R12;
file.Save(...);
```
