### ISSUE TITLE
Loading dxf fails

### ISSUE THREAD

**Issue by paeddib** [IxMilia/Dxf#96]
Loading fails with the attached file Original.dxf in the function DxfMLineStyle/PostParse, with an index out of range exception (cause: different length of lists). 

Loading works with removed section AcDbMlineStyle in the dxf file (AcDbMlineStyle_Removed.dxf).

Would it be possible to change the funktion PostParse, that only DxfMLineStyleElements are added if the lists have the same lengths?

[dxfFiles.zip](https://github.com/IxMilia/Dxf/files/2648786/dxfFiles.zip)

**Comment by brettfo** [comment]
Thanks for finding and filing the issue!  I was incorrectly assuming that all MLINESTYLE elements would specify all values, but your file `Original.dxf` proved that wrong.  I've updated the reader code to not require all values and modified an existing test to cover this case.
